# Generated by Django 5.1 on 2024-09-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_loanapplicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
