# Generated by Django 5.1 on 2024-09-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_loanapplicationmodel_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
