# Generated by Django 5.1 on 2024-09-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_adminmodel_is_superadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_password',
            new_name='user_phoneno',
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='application_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='UserApp.loanapplicationmodel')),
            ],
        ),
    ]
