# Generated by Django 5.1 on 2024-09-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_rename_user_password_usermodel_user_phoneno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplicationmodel',
            old_name='admin',
            new_name='assigned_to',
        ),
    ]
