# Generated by Django 5.1 on 2024-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_rename_admin_loanapplicationmodel_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='work_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
