# Generated by Django 5.1 on 2024-09-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_loanapplicationmodel_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='uploaded_file',
        ),
    ]
