# Generated by Django 5.1 on 2024-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_remove_loanapplicationmodel_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='form_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
