# Generated by Django 5.1 on 2024-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_adminmodel_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='work_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Not selected', 'Not selected')], default='Not selected', max_length=20, null=True),
        ),
    ]
