# Generated by Django 5.1 on 2024-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_adminmodel_admin_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='application_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='mobileno_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
