# Generated by Django 5.1 on 2024-09-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_loanapplicationmodel_application_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.adminmodel'),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.bankmodel'),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='loan_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.loanmodel'),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='status_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.statusmodel'),
        ),
    ]
