# Generated by Django 5.1 on 2024-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_staffselectionmodel_loanapplicationmodel_workstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='work_status',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='UserApp.adminmodel'),
        ),
    ]
