# Generated by Django 5.1 on 2024-09-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_remove_loanapplicationmodel_work_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='cibil_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='cibil_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='document_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_cibil_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_cibil_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_it_payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_phoneno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='it_payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='guaranter_years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranter_year', to='UserApp.yearmodel'),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_year', to='UserApp.yearmodel'),
        ),
    ]
