# Generated by Django 5.1 on 2024-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_yearmodel_loanapplicationmodel_cibil_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='workstatus',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Not selected', 'Not selected')], default='Not selected', max_length=20, null=True),
        ),
    ]
