# Generated by Django 5.1 on 2024-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_remove_usermodel_user_email_usermodel_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='executive_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
