# Generated by Django 5.1 on 2024-11-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_alter_loanapplicationmodel_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='followup_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='StaffAssignmentModel',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('loan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.adminmodel')),
            ],
        ),
    ]
