# Generated by Django 5.1 on 2024-11-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_alter_loanapplicationmodel_followup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignmentmodel',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to='UserApp.adminmodel'),
        ),
        migrations.AddField(
            model_name='staffassignmentmodel',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staffassignmentmodel',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='UserApp.adminmodel'),
        ),
    ]
